name: flutter_boilerplate
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.6.2
  riverpod_annotation: ^2.6.1
  flex_color_scheme: ^8.1.0
  hugeicons: ^0.0.7
  envied: ^1.1.1
  envied_generator: ^1.1.1
  sentry_flutter: ^8.14.1
  flutter_riverpod: ^2.6.1
  permission_handler: ^12.0.0+1
  powersync: ^1.12.2
  supabase_flutter: ^2.8.4
  path: ^1.9.0
  path_provider: ^2.1.5
  sign_in_with_apple: ^7.0.1
  flutter_svg: ^2.0.17
  internet_connection_checker_plus: ^2.7.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
